runtime: nodejs14

service: frontend

handlers:
  - url: /(.*\.(js|css|png|jpg|jpeg|ico|json|svg|woff2))$
    static_files: dist/\1
    upload: dist/(.*\.(js|css|png|jpg|jpeg|ico|json|svg|woff2))$

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
